### PR TITLE
compressors.lib improvment

### PR DESCRIPTION
**Pull request by Yo-L-B**
Changed gain_computer in Peak_compression_gain_mono and RMS_compression_gain_mono for operations above 0dB

### CODE REVIEW

**Comment by sletz** [comment]
@magnetophon: what do to think of this PR ?

**Comment by magnetophon** [comment]
@sletz IDK what to think of it.
@Yo-L-B Could you please explain what this does?

**Comment by Yo-L-B** [comment]
Sure,
Here are the 3 functions of the select3 inner part of the gain computer graphed in Desmos => https://www.desmos.com/calculator/ubva10viu9. (I had to replace ma.EPSILON with 0.0000001)
x is the level (in dB), t the threshold (dB) and k the knee(dB). These last two parameters can be modified at will.
The red part of the function is the one where knee is applied (and modified in this commit) and as you can see, it is a parabola making the transition from 0 to (level-thr) for any value threshold and knee are set.

**Comment by magnetophon** [comment]
@Yo-L-B Thank you, I added the original formula to your desmos as well, and that makes it clear where the original goes wrong.
Thanks for your improvement!

**Comment by sletz** [comment]
So @magnetophon OK for the merge yes?

**Comment by magnetophon** [comment]
Oh, sorry for not being explicit.
Yes, please merge!

**Comment by sletz** [comment]
Done, thanks.

**Pull request merged**
