### PR TITLE
fix for ba.peakholder

### PR DESCRIPTION
**Pull request by dariosanfilippo**

### CODE REVIEW

**Comment by dariosanfilippo** [comment]
Ops, I forgot to change the holt time parameter into samples rather than seconds; I'll fix that in a second.

**Review by sletz — COMMENTED** [review]
[Here](https://faustlibraries.grame.fr/contributing/) we have :
_Some functions use parameters that are [constant numerical expressions](https://faustdoc.grame.fr/manual/syntax/#constant-numerical-expressions). The convention is to label them in capital letters and document them preferably to be constant numerical expressions (or known at compile time in existing libraries)._

Is N in this categorie ?

**Comment by dariosanfilippo** [comment]
I forgot about the convention; it should bi fixed now.

**Comment by sletz** [comment]
Merge in squash mode done in https://github.com/grame-cncm/faustlibraries/commit/7b2b057dc89c3dcb0b2cd6c937d87dc9f54754aa.

**Pull request closed without merging**
