### PR TITLE
add fibonacci functions

### PR DESCRIPTION
**Pull request by DBraun**
This is from discussion w/ @dariosanfilippo on Discord a long time ago. The functions aren't incredibly musical as far as I can tell, but I think the code could be a starting point for interesting things.

#### Example 1
Generate the famous series: [1, 1, 2, 3, 5, 8, 13, ...]
```faust
process = 1 : ba.impulsify : fibonacci(2);
```

#### Example 2
Use the update equation `y = 2*y' + 3*y'' + 4*y'''`
```faust
process  = 1 : ba.impulsify : fibonacciGeneral(waveform{2, 3, 4});
```

#### Example 3
Using `phi` as the golden ratio, produce the sequence `[1, 1-phi, 2-phi, 3-2*phi, 5-3*phi, 8-5*phi, ...]` which converges to zero. Actually this example isn't working for me. Can someone help figure out why?
```faust
PHI = (1+sqrt(5))/2; // golden ratio
process = button("impulse") <: (_>mem) <: _, (mem*(1-PHI)) :> fibonacci(2);
```

### CODE REVIEW

**Comment by dariosanfilippo** [comment]
Thanks, David. There's also this one to generate a list at compile-time if needed:

```
// seq_fibonacci(N); --------------------------------------------------------
//
// First N numbers of the Fibonacci sequence:
//    0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
//
// 0 inputs.
//
// N outputs:
//    y1[n];
//    y2[n];
//    ...;
//    yN-1[n];
//    y[N], the first N numbers in the Fibonacci sequence.
//
// 1 compile-time arguments:
//    N, the first N numbers in the Fibonacci sequence.
//
seq_fibonacci(N) = iterate(N, (0, 1))
    with {
        iterate(1, (A0, A1)) = A0;
        iterate(N, (A0, A1)) = A0 , iterate(N - 1, (A1, A0 + A1));
    };
// -----------------------------------------------------------------------------
```

**Comment by DBraun** [comment]
Thanks. I added that but modified it so that the sequence starts as [1, 1, 2], not with a zero.

Also I realized my mistake earlier. The impulse is actually the sequence [1, -phi] not [1, 1-phi].
```faust
PHI = (1+sqrt(5))/2; // golden ratio
process = (ba.time==0) - ((ba.time==1)*PHI) :> fibonacci(2) : aa.clip(-10, 10);
```
Still, this code explodes due to floating point errors. That's why I put the aa.clip at the end. One can inspect the result easily with Plot First Samples feature in the IDE.

**Comment by sletz** [comment]
The new functions are in the "Meshes" section: does this makes sense ?

**Comment by DBraun** [comment]
I just made a bunch of changes, but now I want approval from @josmithiii and @rmichon. Julius's name wasn't on the code because the `declare foo author "Julius O. Smith III";` metadata wasn't used on his functions. It was just in markdown. This made it more complicated to re-arrange the sections, which I wanted to do in order to add fibonacci. So now the metadata is properly there, and I just want to make sure @josmithiii and @rmichon are ok with it :)

**Review by josmithiii — APPROVED** [review]
Thanks for taking care of all that!

**Comment by sletz** [comment]
Thanks, manually merged, also fixing some of typos in https://github.com/grame-cncm/faustlibraries/commit/1cb4bfa30958694ed5f60b33ad559f5925b798a4 then regenerated.

**Pull request closed without merging**
