### PR TITLE
 tabulate: use int(id+0.5) in .val  (was:  tabulate: use floor(id) in the interpolators)

### PR DESCRIPTION
**Pull request by magnetophon**
Since we are looking for the closest value below id. 
Also: d needs to be positive.

### CODE REVIEW

**Comment by sletz** [comment]
Can you explain what problem this PR solves?

**Comment by magnetophon** [comment]
For .``val``, we want to read the value closest to id, so we take the int of id.
For the lin case we want to interpolate between the closest value below or at id and the one above it.
So we need ``floor(id)``.

To illustrate:
Say we have a table with 3 values, 1, 1.00000001 and 2^24.
``id`` is 0.75, so the final output should be close to 1.
The current implementation will read 1.00000001 and 2^24 and feed it to the interpolator with a negative ``dv``.
The new one will read 1 and 1.00000001 and will have a positive ``dv``.

**Comment by sletz** [comment]
AFAICS `int` and `floor` behave the same for positive value (see https://stackoverflow.com/questions/3300290/cast-to-int-vs-floor). Are you speaking about and issue with negatives values ?

**Comment by magnetophon** [comment]
You are right, I always thought ``int`` was rounding and ``floor`` was rounding down.

That sheds light on another bug though.
For ``.val`` we *do* want the rounded value, not the rounded down one.

**Comment by sletz** [comment]
Thanks.

**Pull request merged**
