### PR TITLE
Fix modalModel and add documention

### PR DESCRIPTION
**Pull request by jkbd**
I already mentioned the error and solution here: [https://github.com/grame-cncm/faust/pull/223](https://github.com/grame-cncm/faust/pull/223). Now I also wrote some documentation.

### CODE REVIEW

**Comment by jkbd** [comment]
@sletz If there is any problem with this pull request please give me a hint. I'm willing to fix it!

**Comment by sletz** [comment]
@rmichon is the guy to ping ((-; Romain knows the libraries much better than me.

**Comment by jkbd** [comment]
I see, thank you. @rmichon how can I help to have my request pulled?

**Comment by rmichon** [comment]
Hi everyone, sorry for the delay, I'm pretty busy these days. Thanks @jkbd for spotting this!

**Pull request merged**
