### PR TITLE
Implementation of The Dattorro Reverb Topology

### PR DESCRIPTION
**Pull request by zerbian**
If the faust libraries are open for contributions, I am happy to implemented the Dattorro Reverb Topology, described in [this paper](https://ccrma.stanford.edu/~dattorro/EffectDesignPart1.pdf).
I am not quite sure how the license in this case works, because I simply translated the Dattorro Topology into Faust code, but I am open for any discussion.

I also have some good sounding presets and UI variants of the basic implementation ready, if needed.

Cheers!
Jakob

### CODE REVIEW

**Comment by sletz** [comment]
Contributions are welcome ! Can you possibly add `Author` and `Licence` lines as in https://github.com/grame-cncm/faustlibraries/blob/master/compressors.lib#L90 ?

**Review by josmithiii — APPROVED** [review]
Looks good!  Agree that you should add 

 declare author dattorro "Your Name"; 
 declare license dattorro "Your License Choice"; 

Since the prefix is "re", I guess there is no need for a longer name such as dattorro_rev, but you might consider it since all other reverbs have either "rev" or "freeverb" in their names.

**Comment by zerbian** [comment]
Thank you for reviewing, what do license do you recommend this type of contribution ?

**Comment by josmithiii** [comment]
> Thank you for reviewing, what license do you recommend this type of contribution ?

For my Faust contributions, I chose STK-4.3.  It's basically the MIT license adding a non-binding request to give us bug fixes/reports.

**Comment by josmithiii** [comment]
Looking better all the time!  Typo: "paramter" - Also, dattorro_orig could be dattorro_rev_default, or dattorro_rev_orig, etc.  What do others think?

**Comment by zerbian** [comment]
I think `dattorro_rev_default` is the most descriptive about its usecase. But I am happy with either.

**Comment by josmithiii** [comment]
+1 - It is easy to set up one's own synonym

**Comment by sletz** [comment]
`dattorro_rev_default` seems better indeed.

**Comment by sletz** [comment]
Did a final typo fix and merged in rebase mode. Thanks !

**Comment by zerbian** [comment]
Thank you!

**Comment by josmithiii** [comment]
Thanks for the contribution!

One final thought, from looking at the paper again: Another nomenclature could be

  tank_rev = full case with all the arguments left open

  dattorro_rev = tank_rev(argumentsFilledInALaDattorro)

I've often heard that reverb architecture referred to as a "tank reverb" over the years, and in the paper, Dattorro characterizes it as a "Simplified plate-class reverberation topology in the style of Griesinger", and then goes on to describe the heart of it as the "Tank" (Section 1.3.2).

**Pull request closed without merging**
