### PR TITLE
rewrite slidingReduce

### PR DESCRIPTION
**Pull request by magnetophon**
This version is much more readable and gives much smaller and clearer
block-diagrams.
It also doesn't have the limitation that maxN needs to be a power of 2.

### CODE REVIEW

**Comment by dariosanfilippo** [comment]
@magnetophon Hey, Bart, have you already tried implementing [this](https://arxiv.org/pdf/cs/0610046.pdf) new max/min filter algorithm in Faust? I've only looked at it and it appears to be the fastest with only three comparisons per sample, but from a quick look at the pseudo-code, I see nested loops so I'm not sure whether that could be done in Faust.

Let me know if you have a look.

Cheers,
Dario

**Comment by magnetophon** [comment]
As discussed on slack:
I read the paper, but didn't understand much.
Since @dariosanfilippo is not sure the other algo is possible in Faust, maybe this PR should be considered for merging until someone can implement a better algo?

**Comment by sletz** [comment]
> This version is much more readable and gives much smaller and clearer
> block-diagrams.

Can you send one example of that?

Is the generated code different? Des it does faster?

**Comment by magnetophon** [comment]
Here's a fully folded out ``ba.slidingMax(15,15)``:
screenshot_20220604_040821
And here's the old version:
screenshot_20220604_041346

The generated code is identical, since the algorithm is identical.

**Comment by sletz** [comment]
Nice ! 

I understand that all `slidingXX` have the "`N`: the number of values to process" as [constant numerical expressions](https://faustdoc.grame.fr/manual/syntax/#constant-numerical-expressions), as documented here: https://faustlibraries.grame.fr/contributing/#new-functions. If yes, the I suggest we add this in the documentation of each function.

**Comment by sletz** [comment]
Hum `N` does not need to be a constant numerical expressions, but `maxn`yes right ?

**Comment by magnetophon** [comment]
So IIUC, you want me to document the fact that maxN needs to be known at compile time, correct?

**Comment by sletz** [comment]
Yes and first "N" should become "n" since capital letters are actually reserved for "known at compile time. Note that this is pure coding conventions  but it helps improving the documentation  quality.

**Comment by magnetophon** [comment]
OK, all done.

I also replaced ``combine`` with ``parallelOp`` and fixed a few documentation typos.

**Comment by sletz** [comment]
Did a bit of code reformatting and fixed some typos. Thanks for the PR !

**Pull request merged**
