### PR TITLE
add ahdsrfqqq, adsrfqqq, asrfqqq, and derivatives

### PR DESCRIPTION
**Pull request by marchingband**

### CODE REVIEW

**Comment by josmithiii** [comment]
Very nice!  Thanks for the contribution

**Comment by DBraun** [comment]
This is great! I've messing around in the IDE now.

1. It seems ok to do `ratio = pow(k, 5) / 100000 : max(ma.EPSILON);` instead of `ratio = pow(k, 5) / 100000 + 0.001;` but what is the justification for 5 and 100000?
2. Should there be another version that has three `k`, one for each of the attack, decay, and release curves?
3. Can you make another version that has a "hold" section too in between attack and decay? 😄

**Comment by DBraun** [comment]
I think pow(k, 5) / 100000 for k [0,20] is effectively the same as pow(q,5)*32 for q [0,1]. It's just a substitution of variables. The second one is probably more interpretable, but the new constants are 5 and 32.

**Comment by marchingband** [comment]
> It seems ok to do ratio = pow(k, 5) / 100000 : max(ma.EPSILON);

The issue comes up when `q==0`, the envelope never reaches 1.0, I do not have a precise understanding of why, I assume it is some floating point hijinx.
using `ma.EPSILON` does not work :( 
0.001 does however, so I will use `pow(q,5)*32 : max(0.001)` unless you have another idea.

I also feel like it may not be idiomatic in faust to add this computation at all, where it is just to improve DX. Perhaps I should just put a note in the docs on how to pick a good number, and leave it up to users? What do you think?

**Comment by marchingband** [comment]
OK I have added hold, added optional independent q's for each segment, and changed the q input parameter to [0..1].
I decided that since it is in the "UI thread" it's ok to have these `pow(q,5)*32 : max(0.001)` computations in the code. Let me know if I should change that!

Thanks for the feedback :)

**Comment by DBraun** [comment]
I'm messing around with this code:
```faust
k_power = hslider("k_power", 8., 1., 16., .001);
ratio_max = hslider("ratio_max", 15., 8., 32., .001);
to_ratio(k) = pow(k, k_power) * ratio_max : max(0.001);
```

Then in these plots `pow` in the legend is `k_power` and `max` is `ratio_max`. The other pars:
attack: 1.0 sec
decay: 0.5 sec
sustain: 0
release: 0.2 sec

image

This looks good. However, if I change the sustain level to 0.5, the linear mode (k close to 1.0) doesn't work well. The line appears to be on the same trajectory. You can rapidly switch between the two images and see the similarity.

image

So I think it would be better if the linear lines (high k values) didn't reach the sustain value so much sooner than other settings. Do you think there's a fix for this? Here's the notebook https://colab.research.google.com/drive/1fnbSr36BTNtzWkPcdCoBiVppGQLHxVLA?usp=sharing

**Comment by DBraun** [comment]
Here's the graph with the 5 and 32 numbers from earlier.
image

**Comment by marchingband** [comment]
@DBraun thanks for those awesome graphs!
I noticed this problem as well.  
The formula for the coefficient from the blog posts is `calc_coef(rate, target) = exp((-1 * log((1.0 + target) / target)) / rate);`  
I imagine that there must be an implicit `1` in this formula, where it always assumes the distance in the y axis to be +/-1. I tried to figure out how to adapt the formula (and I am noticing this variable `magnitude` found its way into my PR [here](https://github.com/marchingband/faustlibraries/blob/2455226f4ecc4fdda129e75926e6689fc2fb0224/envelopes.lib#L697)), but I was not able to ... again, no math background :(  
Is there any chance you could help me here?

**Comment by DBraun** [comment]
I did some guessing and changed the middle portion to this

```faust
         calc_coef(d, rate, target) = exp((-1 * log((d + target) / target)) / rate);

         // calculate our "move" distances
         d1 = 1.-fin;
         d2 = 1.-sus;
         d3 = sus-fin;

         att_ratio = to_ratio(k_att);
         att_rate = ma.SR * att;
         att_coef = calc_coef(d1, att_rate, att_ratio);
         att_base = (1.0 + att_ratio) * (1.0 - att_coef);

         dec_ratio = to_ratio(k_dec);
         dec_rate = ma.SR * dec;
         dec_coef = calc_coef(d2, dec_rate, dec_ratio);
         dec_base = (sus - dec_ratio) * (1.0 - dec_coef);

         rel_ratio = to_ratio(k_rel);
         rel_rate = ma.SR * rel;
         rel_coef = calc_coef(d3, rel_rate, rel_ratio);
         rel_base = (fin - rel_ratio) * (1.0 - rel_coef);
```
Then the graph for attack=1., decay=0.5, sustain=0.5, release=0.5 and a note held for 1.5 sec looks like this
image

For sustain =0.4 it looks like this
image

I wasn't able to get it working for `fin` values other than zero, and I would be fine if it were dropped as a parameter and hard-coded to zero.

**Comment by marchingband** [comment]
eek that's embarrassing, I feel like I must have guessed that as well? Thank you!
I am using your formula with a variety of `final` values and it appears to be working ... what results are you getting that seem wrong?
I am happy to remove `final` if it is not working and not needed.

**Comment by DBraun** [comment]
Yes you hinted at it, thanks.

Here's a graph with `final` set to -1.
attack=1., decay=0.5, sustain=0.5, release=0.5 and a note held for 1.5 sec looks like this

image


It's wrong because it initializes at 0 somehow, and also all the curves seem to each their peak too soon. The note is being held for 1.5 sec. The attack is supposed to be 1 sec, decay is 0.5 sec

**Comment by marchingband** [comment]
I see now thanks. I wasn't able to find much info on this `final` parameter online so I assumed it was meant to be a positive integer. So the envelope never gets to `0` but rather drones quietly all the time instead, which does seem useful. Using a positive integer, adsrfq does SEEM to work correctly for me.

**Comment by DBraun** [comment]
Ah yes final>=0 seems ok.

Here I set final to 0.2 and sustain to 0.6==(1.+0.2)/2 so that the second portion is a straight line.

image

**Comment by DBraun** [comment]
We also must enforce that final >= sustain or less you get stuff like this (final: 0.2, sustain: 0.1)
image

**Comment by marchingband** [comment]
Ok I have added the distance parameter, and added the checks. It seems pretty good now.

**Comment by DBraun** [comment]
One more thing: Can we refactor this:

```faust
calc_coef(rate, target, magnitude) = exp((-1 * log((magnitude + target) / target)) / rate);
```
into
```faust
calc_coef(rate, target, magnitude) = (target/(magnitude + target))^(1/rate); 
```

The first one's c++ is
```c++
output0[i0] = FAUSTFLOAT(std::exp((0.0f - std::log((fTemp0 + float(input2[i0])) / fTemp0)) / float(input0[i0])));
```
but the second's is
```c++
output0[i0] = FAUSTFLOAT(std::pow(fTemp0 / (fTemp0 + float(input2[i0])), 1.0f / float(input0[i0])));
```

**Comment by marchingband** [comment]
That's awesome. I've pushed this change. Thanks!

**Comment by DBraun** [comment]
I haven't benchmarked this, but I think by performing the select operations earlier we can avoid more duplicate operations.

[IDE demo](https://faustide.grame.fr/?autorun=1&voices=8&name=untitled4&inline=aW1wb3J0KCJzdGRmYXVzdC5saWIiKTsKCgphZHNyZnFxcShhdHQsIGRlYywgc3VzLCByZWwsIGZpbiwga19hdHQsIGtfZGVjLCBrX3JlbCwgZ2F0ZSkgPSBlbnZlbG9wZSAKd2l0aCB7CiAgICB1Z2F0ZSA9IGdhdGU-MDsKICAgIHN1c3RhaW4gPSBtYXgoc3VzLCBmaW5hbCk7CiAgICBmaW5hbCA9IG1heCgwLCBmaW4pOwoKICAgIHRvX3JhdGlvKGspID0gcG93KGssIDUpICogMzIgOiBtYXgoMC4wMDEpOwogICAgY2FsY19jb2VmKHJhdGUsIHRhcmdldCwgbWFnbml0dWRlKSA9ICh0YXJnZXQvKG1hZ25pdHVkZSArIHRhcmdldCkpXigxL3JhdGUpOwoKICAgIGZiKHN0YXRlLCB5KSA9IG5leHRTdGF0ZSwgbmV4dFkgCiAgICB3aXRoIHsKICAgICAgICAKICAgICAgICAvLyBTdXBwb3NlIHdlIGhhdmUgTiBidXNlcyBpbiBwYXJhbGxlbCB3aGVyZSBlYWNoIGJ1cyBoYXMgQyBvdXRwdXQgY2hhbm5lbHMuCiAgICAgICAgLy8gV2Ugd2FudCB0byBzZWxlY3QgdGhlIEMgb3V0cHV0cyBvZiB0aGUgaXRoIGJ1cy4KICAgICAgICAvLyBzaS5idXMoTipDKSA6IHNlbGVjdEJ1c0koTiwgQywgaSkgOiBzaS5idXMoQyk7CiAgICAgICAgc2VsZWN0QnVzSShOLCBDLCBpKSA9IHBhcihqLCBDLCBiYS5zZWxlY3RuKE4qQyxpKkMraikpOwogICAgICAgCiAgICAgICAgLy8gdHVwbGUgb2YgcmF0ZSwgY3VydmUsIG1hZ25pdHVkZQogICAgICAgIGF0dF9wYXJzID0gYXR0LCBrX2F0dCwgMS1maW5hbDsKICAgICAgICBkZWNfcGFycyA9IGRlYywga19kZWMsIDEtc3VzdGFpbjsKICAgICAgICByZWxfcGFycyA9IHJlbCwga19yZWwsIHN1c3RhaW4tZmluYWw7CgogICAgICAgIGNvZWZfcGFycyA9IGF0dF9wYXJzLCBkZWNfcGFycywgcmVsX3BhcnMgPDogc2VsZWN0QnVzSSgzLCAzLCBzdGF0ZSk7CiAgICAgICAgcmF0ZSA9IGNvZWZfcGFycyA6IGJhLnNlbGVjdG9yKDAsIDMpIDogXyAqIG1hLlNSOwogICAgICAgIHJhdGlvID0gY29lZl9wYXJzIDogYmEuc2VsZWN0b3IoMSwgMykgOiB0b19yYXRpbzsKICAgICAgICBtYWcgPSBjb2VmX3BhcnMgOiBiYS5zZWxlY3RvcigyLCAzKTsKCiAgICAgICAgY29lZiA9IGNhbGNfY29lZihyYXRlLCByYXRpbywgbWFnKTsKCiAgICAgICAgYXR0X2Jhc2UgPSAxLjAgKyByYXRpbzsKICAgICAgICBkZWNfYmFzZSA9IHN1c3RhaW4gLSByYXRpbzsKICAgICAgICByZWxfYmFzZSA9IGZpbmFsIC0gcmF0aW87CiAgICAgICAgYmFzZSA9IHNlbGVjdDMoc3RhdGUsIHJlbF9iYXNlLCBhdHRfYmFzZSwgZGVjX2Jhc2UpICogKDEuLWNvZWYpOwogICAgICAgICAgICAKICAgICAgICBtaW5pbXVtID0gc2VsZWN0MyhzdGF0ZSwgZmluYWwsIGZpbmFsLCBzdXN0YWluKTsKICAgICAgICBuZXh0WSA9IG1heChtaW5pbXVtLCBtaW4oMSwgYmFzZSArIHkgKiBjb2VmKSk7CiAgICAgICAgbmV4dFN0YXRlID0gc2VsZWN0Mih1Z2F0ZSwKICAgICAgICAgICAgMCwKICAgICAgICAgICAgc2VsZWN0MyhzdGF0ZSwKICAgICAgICAgICAgICAgIDEsCiAgICAgICAgICAgICAgICBzZWxlY3QyKHkgPCAxLjAsIDIsIDEpLAogICAgICAgICAgICAgICAgMgogICAgICAgICAgICApCiAgICAgICAgKTsKICAgIH07CiAgICBlbnZlbG9wZSA9IGZiIH4gKF8sXykgOiAhLCBfOwp9OwoKcHJvY2VzcyA9IGFkc3JmcXFxKAogICAgaHNsaWRlcigiYXR0YWNrIiwgMS4wLCAuMCwgMS4sIC4wMDEpLAogICAgaHNsaWRlcigiZGVjYXkiLCAuNSwgLjAsIDEuLCAuMDAxKSwKICAgIGhzbGlkZXIoInN1c3RhaW4iLCAuNSwgLjAsIDEuLCAuMDAxKSwKICAgIGhzbGlkZXIoInJlbGVhc2UiLCAuMiwgLjAsIDEuLCAuMDAxKSwKICAgIDAuLAogICAgaywgaywgaywKICAgIGJ1dHRvbigiR2F0ZSIpCiAgICApIDogaXQucmVtYXAoMCwgMSwgLS4xLCAuMSkKICAgIHdpdGggewogICAgICAgIGsgPSBoc2xpZGVyKCJrIiwgLjAwMSwgLjAsIDEuLCAuMDAxKTsKICAgIH07).

**Comment by marchingband** [comment]
ahhh ok fantastic, that makes sense, should I make this change?

**Comment by DBraun** [comment]
Actually the attack slider isn't working in that example. I also tried optimizing the `ba.selector` into select3 primitives which turn out to be faster in C++. Here's that [example](https://faustide.grame.fr/?autorun=0&voices=0&name=untitled&inline=aW1wb3J0KCJzdGRmYXVzdC5saWIiKTsKCmFkc3JmcXFxKGF0dCwgZGVjLCBzdXMsIHJlbCwgZmluLCBrX2F0dCwga19kZWMsIGtfcmVsLCBnYXRlKSA9IGVudmVsb3BlIAp3aXRoIHsKICAgIHVnYXRlID0gZ2F0ZT4wOwogICAgc3VzdGFpbiA9IG1heChzdXMsIGZpbmFsKTsKICAgIGZpbmFsID0gbWF4KDAsIGZpbik7CgogICAgdG9fcmF0aW8oaykgPSBwb3coaywgNSkgKiAzMiA6IG1heCgwLjAwMSk7CiAgICBjYWxjX2NvZWYocmF0ZSwgdGFyZ2V0LCBtYWduaXR1ZGUpID0gKHRhcmdldC8obWFnbml0dWRlICsgdGFyZ2V0KSleKDEvcmF0ZSk7CgogICAgZmIoc3RhdGUsIHkpID0gbmV4dFN0YXRlLCBuZXh0WSAKICAgIHdpdGggewogICAgICAgIAogICAgICAgIC8vIFN1cHBvc2Ugd2UgaGF2ZSAzIGJ1c2VzIGluIHBhcmFsbGVsIHdoZXJlIGVhY2ggYnVzIGhhcyAzIG91dHB1dCBjaGFubmVscy4KICAgICAgICAvLyBXZSB1c2UgaW5kZXggaSB0byBzZWxlY3QgdGhlIHBhcmFtZXRlcnMgZnJvbSB0aGUgaXRoIGJ1cy4KICAgICAgICBzZWxlY3RCdXMoaSkgPSByby5pbnRlcmxlYXZlKDMsIDMpIDogcGFyKGosIDMsIHNlbGVjdDMoaSkpOwogICAgICAgCiAgICAgICAgLy8gdHVwbGUgb2YgcmF0ZSwgY3VydmUsIG1hZ25pdHVkZQogICAgICAgIGF0dF9wYXJzID0gYXR0LCBrX2F0dCwgMS1maW5hbDsKICAgICAgICBkZWNfcGFycyA9IGRlYywga19kZWMsIDEtc3VzdGFpbjsKICAgICAgICByZWxfcGFycyA9IHJlbCwga19yZWwsIHN1c3RhaW4tZmluYWw7CgogICAgICAgIGNvZWZfcGFycyA9IGF0dF9wYXJzLCBkZWNfcGFycywgcmVsX3BhcnMgOiBzZWxlY3RCdXMoc3RhdGUpOwogICAgICAgIHJhdGUgPSBjb2VmX3BhcnMgOiBiYS5zZWxlY3RvcigwLCAzKSA6IF8gKiBtYS5TUjsKICAgICAgICByYXRpbyA9IGNvZWZfcGFycyA6IGJhLnNlbGVjdG9yKDEsIDMpIDogdG9fcmF0aW87CiAgICAgICAgbWFnID0gY29lZl9wYXJzIDogYmEuc2VsZWN0b3IoMiwgMyk7CgogICAgICAgIGNvZWYgPSBjYWxjX2NvZWYocmF0ZSwgcmF0aW8sIG1hZyk7CgogICAgICAgIGF0dF9iYXNlID0gMS4wICsgcmF0aW87CiAgICAgICAgZGVjX2Jhc2UgPSBzdXN0YWluIC0gcmF0aW87CiAgICAgICAgcmVsX2Jhc2UgPSBmaW5hbCAtIHJhdGlvOwogICAgICAgIGJhc2UgPSBzZWxlY3QzKHN0YXRlLCByZWxfYmFzZSwgYXR0X2Jhc2UsIGRlY19iYXNlKSAqICgxLi1jb2VmKTsKICAgICAgICAgICAgCiAgICAgICAgbWluaW11bSA9IHNlbGVjdDMoc3RhdGUsIGZpbmFsLCBmaW5hbCwgc3VzdGFpbik7CiAgICAgICAgbmV4dFkgPSBtYXgobWluaW11bSwgbWluKDEsIGJhc2UgKyB5ICogY29lZikpOwogICAgICAgIG5leHRTdGF0ZSA9IHNlbGVjdDIodWdhdGUsCiAgICAgICAgICAgIDAsCiAgICAgICAgICAgIHNlbGVjdDMoc3RhdGUsCiAgICAgICAgICAgICAgICAxLAogICAgICAgICAgICAgICAgc2VsZWN0Mih5IDwgMS4wLCAyLCAxKSwKICAgICAgICAgICAgICAgIDIKICAgICAgICAgICAgKQogICAgICAgICk7CiAgICB9OwogICAgZW52ZWxvcGUgPSBmYiB-IChfLF8pIDogISwgXzsKfTsKCnByb2Nlc3MgPSBhZHNyZnFxcSgKICAgIGhzbGlkZXIoImF0dGFjayIsIDEuMCwgLjAsIDEuLCAuMDAxKSwKICAgIGhzbGlkZXIoImRlY2F5IiwgLjUsIC4wLCAxLiwgLjAwMSksCiAgICBoc2xpZGVyKCJzdXN0YWluIiwgLjUsIC4wLCAxLiwgLjAwMSksCiAgICBoc2xpZGVyKCJyZWxlYXNlIiwgLjIsIC4wLCAxLiwgLjAwMSksCiAgICAwLiwKICAgIGssIGssIGssCiAgICBidXR0b24oIkdhdGUiKQogICAgKSA6IGl0LnJlbWFwKDAsIDEsIC0uNSwgLjUpCiAgICB3aXRoIHsKICAgICAgICBrID0gaHNsaWRlcigiayIsIC4wMDEsIC4wLCAxLiwgLjAwMSk7CiAgICB9Ow%3D%3D) but unfortunately the attack slider is not working in the same way as before.

**Comment by DBraun** [comment]
I fixed it. The `coef_pars` were ordered incorrectly. Here's the [update](https://faustide.grame.fr/?autorun=0&voices=0&name=untitled&inline=aW1wb3J0KCJzdGRmYXVzdC5saWIiKTsKCmFkc3JmcXFxKGF0dCwgZGVjLCBzdXMsIHJlbCwgZmluLCBrX2F0dCwga19kZWMsIGtfcmVsLCBnYXRlKSA9IGVudmVsb3BlIAp3aXRoIHsKICAgIHVnYXRlID0gZ2F0ZT4wOwogICAgc3VzdGFpbiA9IG1heChzdXMsIGZpbmFsKTsKICAgIGZpbmFsID0gbWF4KDAsIGZpbik7CgogICAgdG9fcmF0aW8oaykgPSBwb3coaywgNSkgKiAzMiA6IG1heCgwLjAwMSk7CiAgICBjYWxjX2NvZWYocmF0ZSwgdGFyZ2V0LCBtYWduaXR1ZGUpID0gKHRhcmdldC8obWFnbml0dWRlICsgdGFyZ2V0KSleKDEvcmF0ZSk7CgogICAgZmIoc3RhdGUsIHkpID0gbmV4dFN0YXRlLCBuZXh0WSAKICAgIHdpdGggewogICAgICAgIAogICAgICAgIC8vIFN1cHBvc2Ugd2UgaGF2ZSAzIGJ1c2VzIGluIHBhcmFsbGVsIHdoZXJlIGVhY2ggYnVzIGhhcyAzIG91dHB1dCBjaGFubmVscy4KICAgICAgICAvLyBXZSB1c2UgaW5kZXggaSB0byBzZWxlY3QgdGhlIGNoYW5uZWxzIGZyb20gdGhlIGl0aCBidXMuCiAgICAgICAgc2VsZWN0QnVzKGkpID0gcm8uaW50ZXJsZWF2ZSgzLCAzKSA6IHBhcihqLCAzLCBzZWxlY3QzKGkpKTsKICAgICAgIAogICAgICAgIC8vIHR1cGxlIG9mIHJhdGUsIGN1cnZlLCBtYWduaXR1ZGUKICAgICAgICBhdHRfcGFycyA9IGF0dCwga19hdHQsIDEtZmluYWw7CiAgICAgICAgZGVjX3BhcnMgPSBkZWMsIGtfZGVjLCAxLXN1c3RhaW47CiAgICAgICAgcmVsX3BhcnMgPSByZWwsIGtfcmVsLCBzdXN0YWluLWZpbmFsOwoKICAgICAgICBjb2VmX3BhcnMgPSByZWxfcGFycywgYXR0X3BhcnMsIGRlY19wYXJzIDogc2VsZWN0QnVzKHN0YXRlKTsKICAgICAgICByYXRlID0gY29lZl9wYXJzIDogYmEuc2VsZWN0b3IoMCwgMykgOiBfICogbWEuU1I7CiAgICAgICAgcmF0aW8gPSBjb2VmX3BhcnMgOiBiYS5zZWxlY3RvcigxLCAzKSA6IHRvX3JhdGlvOwogICAgICAgIG1hZyA9IGNvZWZfcGFycyA6IGJhLnNlbGVjdG9yKDIsIDMpOwoKICAgICAgICBjb2VmID0gY2FsY19jb2VmKHJhdGUsIHJhdGlvLCBtYWcpOwoKICAgICAgICBhdHRfYmFzZSA9IDEuMCArIHJhdGlvOwogICAgICAgIGRlY19iYXNlID0gc3VzdGFpbiAtIHJhdGlvOwogICAgICAgIHJlbF9iYXNlID0gZmluYWwgLSByYXRpbzsKICAgICAgICBiYXNlID0gc2VsZWN0MyhzdGF0ZSwgcmVsX2Jhc2UsIGF0dF9iYXNlLCBkZWNfYmFzZSkgKiAoMS4tY29lZik7CiAgICAgICAgICAgIAogICAgICAgIG1pbmltdW0gPSBzZWxlY3QzKHN0YXRlLCBmaW5hbCwgZmluYWwsIHN1c3RhaW4pOwogICAgICAgIG5leHRZID0gbWF4KG1pbmltdW0sIG1pbigxLCBiYXNlICsgeSAqIGNvZWYpKTsKICAgICAgICBuZXh0U3RhdGUgPSBzZWxlY3QyKHVnYXRlLAogICAgICAgICAgICAwLAogICAgICAgICAgICBzZWxlY3QzKHN0YXRlLAogICAgICAgICAgICAgICAgMSwKICAgICAgICAgICAgICAgIHNlbGVjdDIoeSA8IDEuMCwgMiwgMSksCiAgICAgICAgICAgICAgICAyCiAgICAgICAgICAgICkKICAgICAgICApOwogICAgfTsKICAgIGVudmVsb3BlID0gZmIgfiAoXyxfKSA6ICEsIF87Cn07Cgpwcm9jZXNzID0gYWRzcmZxcXEoCiAgICBoc2xpZGVyKCJhdHRhY2siLCAxLjAsIC4wLCAxLiwgLjAwMSksCiAgICBoc2xpZGVyKCJkZWNheSIsIC41LCAuMCwgMS4sIC4wMDEpLAogICAgaHNsaWRlcigic3VzdGFpbiIsIC41LCAuMCwgMS4sIC4wMDEpLAogICAgaHNsaWRlcigicmVsZWFzZSIsIC4yLCAuMCwgMS4sIC4wMDEpLAogICAgMC4sCiAgICBrLCBrLCBrLAogICAgYnV0dG9uKCJHYXRlIikKICAgICkgOiBpdC5yZW1hcCgwLCAxLCAtLjUsIC41KQogICAgd2l0aCB7CiAgICAgICAgayA9IGhzbGlkZXIoImsiLCAuMDAxLCAuMCwgMS4sIC4wMDEpOwogICAgfTs%3D). I think you should push it with any other edits you'd like to make.

**Comment by DBraun** [comment]
I think I don't like the output in an edge case. Try these settings for `adsrfqqq`
* attack: 1.0 sec
* decay 1.0 sec
* sustain: 0.1
* release: 0.1
* q: 1.0 (fully linear)

When you release the gate at a high value, the actual time to release is much more than 0.1 sec. This is why I ended up keeping tracking of the `y` value at the moment of release (`y_at_release`) in the `adsr_bias` functions.

Last, there are more places where you could refactor the code so that you re-use functions, like what you did for
`arqq(att, rel, k_att, k_rel, gate) = asrfqq(att, 1.0, rel, 0.0, k_att, k_rel, gate);`

It would be good to use the select3 as late as possible to get faster C++ code (lower priority for now..).

**Comment by sletz** [comment]
I was think the @DBraun bias versions (juste merged...) were more general? So is there any need to continue working here ?

**Comment by marchingband** [comment]
I am pretty sure the bias functions completely replace all these so we can close it.

**Comment by sletz** [comment]
Replaced by more general `xx_bias`versions.

**Pull request closed without merging**
