### PR TITLE
Fix ADSR envelope: 

### PR DESCRIPTION
**Pull request by iBundin**
a  note could be released before sustain stage of the envelope.

### CODE REVIEW

**Comment by sletz** [comment]
Thanks, I'll check it ASAP.

**Comment by orlarey** [comment]
We need to check because this is a rather different behavior. Perhaps a new function is needed instead...

**Comment by iBundin** [comment]
> We need to check because this is a rather different behavior. Perhaps a new function is needed instead...

In my opinion, current ADSR implementation is incorrect, because rDelta does not depend on the envelope output level which could be different from _sustain_, thus _release time_ is always different depending on attack, decay, and the moment gate becomes 0.

**Comment by sletz** [comment]
From @orlarey : 

Concerning the ADSR, the current behavior is the intended one: the release part starts as soon as the gate signal ends. 

Here is a link to experiment with: 

https://faustide.grame.fr/?autorun=0&voices=0&name=adsr&inline=aW1wb3J0KCJzdGRmYXVzdC5saWIiKTsKCnByb2Nlc3MgPSBiYS5wdWxzZW4oYmEuc2VjMnNhbXAoMSowLjE3KSwgYmEuc2VjMnNhbXAoMSkpIDogQCgxMDAwMCkgCiAgICAgICAgPDogXywgZW4uYWRzcigwLjEsIDAuMSwgMC43LCAwLjUpOw%3D%3D

Three cases are attached. But I understand that other behaviors could be needed... 
Screen Shot 2021-05-09 at 12 10 14
Screen Shot 2021-05-09 at 12 10 53
Screen Shot 2021-05-09 at 12 11 34

**Comment by orlarey** [comment]
@iBundin, I did some tests. As expected the performances of the two adsr are the same. Moreover, as noted by Oleg, your version performs exactly as the old one. It has a constant release time instead of a constant release slope. This implies a more predictable behavior with very short gates.  Therefore it could also make sense to just replace the current version as you initially suggested. What do you think @sletz ?
ADSR performances

**Comment by sletz** [comment]
Its probably OK to change the ADSR release behaviour, but @orlarey you can ask on Faust mail lists to be sure?

**Comment by orlarey** [comment]
Merged

**Pull request closed without merging**
