### PR TITLE
added fractional-index rdtable and rwtable

### PR DESCRIPTION
**Pull request by dariosanfilippo**
@sletz is this better?

### CODE REVIEW

**Comment by sletz** [comment]
Yes this one can be merged safely. Waiting for @josmithiii feedback then.

**Review by josmithiii — APPROVED** [review]
Thanks for this needed fundamental contribution!
Names well chosen.  Nice and clear coding style.
Good use of existing functions.
I think the doc should allow idx to range from 0 to N, not N-1.
Consider the first-order case, for example.
I assume there is a test program somewhere;
it would be nice to make that available somehow.
What I normally did was put a cleaned-up version of one of my tests in demos.lib.
Really short tests can go in the function comments,
such as "Example:".

**Comment by dariosanfilippo** [comment]
@josmithiii, thanks for taking the time to check this out. :-)

You're right about the order not looking good: I think that the mismatch is the fact that, in the formula, for N=1, k takes both 0 and 1, whereas in Faust we only have one iteration for N = 1 the way I wrote the code. Essentially, what I thought was an order N was actually an N-1 order, does that make sense? So I think that idx currently runs from 0 to N (actual N :-)), right?

I could just change it to "N + 1" in the iterations and we should be good for that, I guess.

I will put together a few examples then. There's already a small one at line 508 showing that a 5th-order interpolator already outputs a clean signal with only a 16-point table of a sinewave.

Thanks,
Dario

**Comment by josmithiii** [comment]
I think we need to clearly distinguish between "order" and "number of points".  For example, we could say
"// Nth-order Lagrange interpolator to interpolate between a set of NP = N+1 points."
or something like that.

**Comment by dariosanfilippo** [comment]
Exactly, that's what I had in mind. I'll put together a few simple examples, I'll fix that, and I'll commit the changes shortly.

Ciao,
Dario

**Comment by josmithiii** [comment]
Sounds good, and I suppose the given example is enough unless you can think of coverage to add.

**Comment by dariosanfilippo** [comment]
Great, I pushed the changes. It should be OK now.

Thanks for your help, Julius. :-)

Dario

**Comment by josmithiii** [comment]
Thanks for your very welcome contribution!

**Comment by sletz** [comment]
Is it ready to be merged ?

**Comment by dariosanfilippo** [comment]
@josmithiii the only thing left to be fixed was the centring after shifting N in the iterations, which is now consistent with your documents, taking place at N/2.

On a different note, I think that we should change os.sinwaveform as it accumulates error over time, especially in single-precision, whereas this doesn't:

S = 16
sin(2*ma.PI*ba.period(S)/S);

**Comment by dariosanfilippo** [comment]
@sletz @josmithiii 

It all seems to work correctly so it should be OK to merge:

```
import("stdfaust.lib");
lagrange_h(N, idx) = par(n, N + 1, prod(k, N + 1, f(n, k)))
    with {
        f(n, k) = ((idx - k) * (n != k) + (n == k)) / ((n - k) + (n == k));
    };

lagrangeN(N, idx) = lagrange_h(N, idx) ,
                    si.bus(N + 1) : ro.interleave(N + 1, 2) : par(i, N + 1, *) :> _;
frdtable(N, S, init, idx) =
    lagrangeN(N, f_idx, par(i, N+1, table(i_idx - int(N / 2) + i)))
    with {
        table(j) = rdtable(S, init, int(ma.modulo(j, S)));
        f_idx = ma.frac(idx) + int(N / 2);
        i_idx = int(idx);
    };
frwtable(N, S, init, w_idx, x, r_idx) =
    lagrangeN(N, f_idx, par(i, N+1, table(i_idx - int(N / 2) + i)))
    with {
        table(j) = rwtable(S, init, w_idx, x, int(ma.modulo(j, S)));
        f_idx = ma.frac(r_idx) + int(N / 2);
        i_idx = int(r_idx);
    };
N = 4;
S = 16;
sine = sin((ba.period(S) / S) * 2 * ma.PI);
hqsine = sin(os.phasor(2 * ma.PI, 1000));
ridx = os.phasor(S, 1000);
widx = int(ba.period(S));
table1 = rdtable(S, sine, int(ridx));
table2 = rwtable(S, .0, widx, sine, int(ridx));
ftable1 = frdtable(N, S, sine, ridx);
ftable2 = frwtable(N, S, .0, widx, sine, ridx);
process =   table1 ,
            table2 ,
            ftable1 ,
            ftable2 ,
            hqsine ,
            hqsine - ftable1 ,
            hqsine - ftable2;

```

**Pull request merged**
