### PR TITLE
Optimization of quantizers.lib

### PR DESCRIPTION
**Pull request by CesarChaussinand**
I modified the library in hope it would be more efficient. 
I can't be sure of the results since i didn't find the statistic tools @sletz used last time (i used `faust -lang fir` but didn't find the statistics). I still get the feeling the whole logic behind this library could be improved.

I couldn't use `ba.tabulate` in the faust web ide or the cli tool (`ERROR : undefined symbol : tabulate`) so i copy-pasted the function inside this file. Is there a problem with basics.lib or did i miss something ?

@rmichon

### CODE REVIEW

**Comment by rmichon** [comment]
Ok, I merged your pull request, but there was a pretty massive conflict for some reasons that I kind of blindly fixed. @CesarChaussinand could you double check that the version of quantizers.lib on this repository corresponds to what you expect? 

To answer your question about ba.tabulate, I'm not sure what you mean since ba.tabulate doesn't exists ;).

**Comment by CesarChaussinand** [comment]
I found the tabulate function at line 685 in the basics.lib file of the master branch. It may be a problem to have a copy of a function from another library but it's necessary for quantizers.lib to work so i copied it to avoid breaking the library.

**Comment by sletz** [comment]
`Tabulate` is in the git repo https://github.com/grame-cncm/faustlibraries/blob/master/basics.lib#L685, but not deployed in the Faust IDE.

**Comment by CesarChaussinand** [comment]
Should i have waited for the deployment of tabulate or is it fine to change it afterward ?

**Comment by sletz** [comment]
You'll have to use the` ba. `version yes.

**Comment by sletz** [comment]
done in https://github.com/grame-cncm/faustlibraries/commit/56f81f383dfa555dbcd27afc22f0a146819291e7

**Pull request merged**
